### PR TITLE
OCPBUGS-11850: Rebase etcd-3.5.8 into openshift-4.14

### PR DESCRIPTION
**Pull request by Elbehery**
This PR rebases etcd 3.5.8 into openshift-4.14. 

Resolves https://issues.redhat.com/browse/OCPBUGS-11850. 
It uses `git rebase --rebase-merges --fork-point v3.5.6 v3.5.8 `

running `make` shows

```
SUCCESS: etcd_build (GOARCH=amd64)
./bin/etcd --version
etcd Version: 3.5.8
Git SHA: 3106d5ea8
Go Version: go1.19.6
Go OS/Arch: darwin/amd64
./bin/etcdctl version
etcdctl version: 3.5.8
API version: 3.5
./bin/etcdutl version
etcdutl version: 3.5.8
API version: 3.5
```

### CODE REVIEW

**Comment by tjungblu** [comment]
recovery bootstrap failure seems to be related to https://redhat-internal.slack.com/archives/C01CQA76KMX/p1684146019667459

**Comment by Elbehery** [comment]
> recovery bootstrap failure seems to be related to 

shall we override ?

**Comment by neisw** [comment]
/retest-required

Need the required tests to be passing in order to merge.

**Comment by tjungblu** [comment]
/lgtm

I've manually validated the memory usage isn't impacted by the new golang version. I will await the result of the nightly jobs tomorrow, the current results look promising for a merge tomorrow.

**Comment by tjungblu** [comment]
/label backport-risk-assessed

not an actual backport

**Comment by tjungblu** [comment]
@geliu2016 could you add the CPA label please when you find some time? I think the branch config is a little confused about the required labels :)

**Comment by tjungblu** [comment]
/retitle OCPBUGS-11850: Rebase etcd-3.5.8 into openshift-4.14

**Comment by tjungblu** [comment]
/label jira/valid-bug

bug is valid, there's no dependent branch config for 4.15 yet

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
