### PR TITLE
Bug 2077498: Merge Upstream etcd 3.5.3 into Openshift 4.10

### PR DESCRIPTION
**Pull request by dusk125**
Basis for 3.5.3 merge into openshift-4.10.

- [x] Need to verify 3.5.3+picklist against this PR to ensure that no downstream picks were clobbered.

This PR was generated by:
1. Merge upstream-3.5.3 into openshift-4.10, taking 'theirs' (upstream) on conflict.
2. Took [picklist](https://gist.github.com/deads2k/f280a34f899c45f4e84ddeb638df96d4) and cherry-picked each commit hash onto a branch based on the upstream-3.5.3 tag.
3. Create PR, from step 1, against remote/openshift-4.10
4. Diff'ed branches from steps 1 and 2 to get picks that were clobbered by the merge (step 1).
5. Re-picked the commit hashes from step 4; updated PR.

### CODE REVIEW

**Comment by dusk125** [comment]
/retitle Bug 2077498: Merge Upstream etcd 3.5.3 into Openshift 4.10

**Review by geliu2016 — APPROVED** [review]
/lgtm

**Comment by Elbehery** [comment]
@hasbro17 this passed the test now

cc @dusk125

**Pull request merged**
