### PR TITLE
OCPBUGS-1023: Rebase openshift/etcd 4.8 onto 3.4.21

### PR DESCRIPTION
**Pull request by tjungblu**
generated with:

> git rebase --rebase-merges --fork-point v3.4.14 v3.4.21

the manually merging and fixing conflicts using:
> git merge --no-commit origin/openshift-4.8

### CODE REVIEW

**Comment by hasbro17** [comment]
/label backport-risk-assessed
/approve

Nice work preserving the upstream carry commit:
https://github.com/openshift/etcd/commit/425db156a396c8eae01eea26c20baca100f50ab0

**Comment by tjungblu** [comment]
regarding the unit test: https://github.com/openshift/release/pull/32857

**Pull request merged**
