### PR TITLE
OCPBUGS-26925: Rebase etcd 3.5.11 openshift 4.13

### PR DESCRIPTION
**Pull request by Elbehery**
This PR rebases etcd 3.5.11 into openshift-4.13.

This PR has been created by this workflow 

- `git rebase --rebase-merges --fork-point v3.5.9 v3.5.11` ( rebasing the changes from upstream 3.5.9 --> 3.5.11 )
- `git cherry-pick 61a5f1cdbf200a036c2fa3fd99e551c1968c7c14` to cherrypick the downstream changes ([commit](https://github.com/openshift/etcd/commit/61a5f1cdbf200a036c2fa3fd99e551c1968c7c14))
- `git cherry-pick 788475c001d39d97f0e0052514ed77d22cbdffcf` to cherrypick the downstream changes ([commit](https://github.com/openshift/etcd/commit/788475c001d39d97f0e0052514ed77d22cbdffcf))

After rebasing, running `make` locally produce 

```
SUCCESS: etcd_build (GOARCH=amd64)
./bin/etcd --version
etcd Version: 3.5.11
Git SHA: fe40c0786
Go Version: go1.21.1
Go OS/Arch: darwin/amd64
./bin/etcdctl version
etcdctl version: 3.5.11
API version: 3.5
./bin/etcdutl version
etcdutl version: 3.5.11
API version: 3.5
```

skipped commits 

- https://github.com/openshift/etcd/commit/3734896c1ab0eb955e49374d30b0cf4d84b9deff
- https://github.com/openshift/etcd/commit/7efbc019a20e4c025d482749d49d0d72892dbfe1

cc @hasbro17 @dusk125 @tjungblu @soltysh @deads2k

### CODE REVIEW

**Comment by tjungblu** [comment]
blocking payload looks OK, there are some unrelated failures in image registry availability. BM didn't run because of missing capacity on installation.

/lgtm

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
