### PR TITLE
ETCD-202: bump etcd v3.5.0

### PR DESCRIPTION
**Pull request by hexfusion**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by hexfusion** [comment]
Quorum guard failures fixed by 

https://github.com/openshift/cluster-etcd-operator/pull/636

**Comment by hexfusion** [comment]
unit tests should pass with https://github.com/openshift/release/pull/20773. they pass locally so the issue is with CI config.

**Comment by lilic** [comment]
/retest

PR was merged.

**Pull request merged**
