### PR TITLE
OCPBUGS-15859: [4.13] Rebase openshift/etcd to 3.5.9

### PR DESCRIPTION
**Pull request by tjungblu**
Essentially what we've done to 4.14, just in one go:

* pick the rebase script
* rebase via forkpoint to the latest release
* pick the golang updates
* pick the upstream work for rev bumps
* pick adding the etcdutl into the docker image

```
git rebase --rebase-merges --fork-point v3.5.6 v3.5.9
git cherry-pick 4b310a07331a661991e7f137b51dc95645837172
git cherry-pick dc7b2599a2f57f4f041cd837a6d5455084392fa9
git cherry-pick cfa79a5d17c0dbbc7c3bbb71af6c4e6c9ab7d802
git cherry-pick a66a9b83109630f67526ada6b556fe2cb4d3673d
git cherry-pick 0970055c1e38f7c9902037b6e4c1ea52db172c6b
```

### CODE REVIEW

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by tjungblu** [comment]
/override ci/prow/unit 

unit tests will work again after the dockerfile has been reconciled in the release repo

**Pull request merged**
