### PR TITLE
UPSTREAM: <carry>: add --experimental-max-learner flag

### PR DESCRIPTION
**Pull request by hexfusion**
This PR is a manual cherry-pick of https://github.com/etcd-io/etcd/pull/13377 into openshift-4.10

Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

/hold for testing

### CODE REVIEW

**Comment by hexfusion** [comment]
configmap-scale is physically broken. 
```
Collecting ripsaw-cli from git+https://github.com/cloud-bulldozer/benchmark-operator.git/#egg=ripsaw-cli&subdirectory=cli
  Cloning https://github.com/cloud-bulldozer/benchmark-operator.git/ to /tmp/pip-build-zgquwxtm/ripsaw-cli
ripsaw-cli requires Python '>=3.8' but the running Python is 3.6.8
```

**Review by hasbro17 — APPROVED** [review]
/lgtm

**Comment by hexfusion** [comment]
infra fail
/retest e2e-aws

**Comment by hexfusion** [comment]
manually adding tags as these are not actually required during 4.10 dev cycle

**Pull request merged**
