### PR TITLE
OCPBUGS-32768: Revert "OCPBUGS-31644: Rebase etcd 3.5.13 openshift 4.15"

### PR DESCRIPTION
**Pull request by Elbehery**
Reverts openshift/etcd#260

### CODE REVIEW

**Comment by dusk125** [comment]
To add some context, we're reverting this to have openshift/etcd stay in sync with the Go version expected at a given Openshift version: for 4.15, that's 1.20.

/lgtm

**Comment by Elbehery** [comment]
> To add some context, we're reverting this to have openshift/etcd stay in sync with the Go version expected at a given Openshift version: for 4.15, that's 1.20.
> 
> /lgtm

Thanks @dusk125 .. is there a jira tag for this ?

**Comment by Elbehery** [comment]
cc @soltysh  just as context, this is for `microshift`

can we label `jira/valid` please ?

**Comment by soltysh** [comment]
Manually overriding to unblock microshift
/remove-label jira/invalid-bug
/label jira/valid-bug

**Pull request merged**
