### PR TITLE
Bug 1806752: [release 4.4] Archive data dir if unstarted 4.4

### PR DESCRIPTION
**Pull request by retroflexer**
This is a manual cherry pick of PR#29 to merge into openshift-4.4.
Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by hexfusion** [comment]
/hold 

why do we have 6 commits here?

**Comment by retroflexer** [comment]
Really? Hmm..

**Comment by retroflexer** [comment]
> why do we have 6 commits here?
Fixed it.
PTAL.

**Comment by retroflexer** [comment]
@hexfusion Can you add lgtm again?

**Pull request merged**
