### PR TITLE
OCPBUGS-34690: Rebase etcd 3.5.14 openshift 4.16

### PR DESCRIPTION
**Pull request by Elbehery**
This PR rebases etcd 3.5.14 into openshift-4.16.

After rebasing, running make locally produce

```
SUCCESS: etcd_build (GOARCH=amd64)
./bin/etcd --version
etcd Version: 3.5.14
Git SHA: b8e830c20
Go Version: go1.21.10
Go OS/Arch: darwin/amd64
./bin/etcdctl version
etcdctl version: 3.5.14
API version: 3.5
./bin/etcdutl version
etcdutl version: 3.5.14
API version: 3.5
```

This PR drops `go toolchain` in this [commit](https://github.com/openshift/etcd/pull/274/commits/c1e70885bdb77abe7e2a56c616a9101c0308b28f) directive since the image stream in ci still on `go1.20`

cc @openshift/openshift-team-etcd

### CODE REVIEW

**Comment by soltysh** [comment]
We've landed master in https://github.com/openshift/etcd/pull/273
/remove-label jira/invalid-bug
/label jira/valid-bug

/hold

**Comment by tjungblu** [comment]
/hold cancel

4.16.0 is done, let's merge this

**Comment by tjungblu** [comment]
@soltysh I think you have to hit the merge button :rofl: the branch config wasn't found again

**Pull request merged**
