### PR TITLE
Add a flowchart to explain the discover initial cluster logic

### PR DESCRIPTION
**Pull request by retroflexer**
Adding the flow chart explaining the logic of the discovery of the initial cluster.

The source for the flowchart can be found here:
https://lucid.app/lucidchart/invitations/accept/inv_df0d2c1d-e237-42b6-8101-70a5d5d43987?viewport_loc=-327%2C-323%2C2428%2C2461%2C0_0
Please read https://github.com/etcd-io/etcd/blob/master/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by hexfusion — COMMENTED** [review]
thanks for doing this, should we stub out a markdown doc and outline a little bit more about `discover-initial-cluster` maybe just high-level what it does where the source is located and a link to the source for the graph in case it ever needs to be changed?

**Comment by hexfusion** [comment]
I think we need to make the PR against master, for now, we can probably avoid BZ workflow for text only changes to repo.

**Review by hexfusion — CHANGES_REQUESTED** [review]
actually I thought this was against the operator repo can we add that to docs/ please

**Comment by retroflexer** [comment]
Moving all documentation to cluster-etcd-operator.

/close

**Pull request closed without merging**
