### PR TITLE
Bug 2097073: cherry-pick fix:etcd-mixin:use-predictLinear-insteadof-increase

### PR DESCRIPTION
**Pull request by Elbehery**
This PR is a manual cherry-pick of upstream https://github.com/etcd-io/etcd/pull/14196

Signed-off-by: Mustafa Elbehery <melbeher@redhat.com>

### CODE REVIEW

**Comment by tjungblu** [comment]
you can safe yourself the trouble here, the operator takes the alert straight from upstream: https://github.com/openshift/cluster-etcd-operator/blob/master/jsonnet/jsonnetfile.json#L7-L8

**Comment by Elbehery** [comment]
Cool, now we dont have to do anything :)

**Comment by tjungblu** [comment]
well, you have to update the alerts, checkout:
https://github.com/openshift/cluster-etcd-operator/blob/master/docs/HACKING.md#update-alerts

**Pull request closed without merging**
