### PR TITLE
UPSTREAM <carry>: Add range response KV length as a metric

### PR DESCRIPTION
**Pull request by tjungblu**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by tjungblu** [comment]
/hold

testing this out for alerting possibilities

**Comment by Elbehery** [comment]
good addition 👍🏽

**Comment by Elbehery** [comment]
@tjungblu  do u need `lgtml` here ? .. 

i see `/hold` above

**Comment by Elbehery** [comment]
@tjungblu do we need this or close it ?

**Pull request closed without merging**
