### PR TITLE
OCPBUGS-22835: [4.13] Rebase openshift/etcd to 3.5.10

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Comment by tjungblu** [comment]
/hold

need to redo the go mod file apparently

**Comment by tjungblu** [comment]
/override ci/prow/unit

unrelated build failure

**Comment by dusk125** [comment]
It looks like another go mod update needs to be run
```go: go.etcd.io/bbolt@v1.3.8 requires
	github.com/stretchr/testify@v1.8.1: missing go.sum entry; to add it:
	go mod download github.com/stretchr/testify
must be run from 'go.etcd.io/etcd/v3' module directory```

**Comment by tjungblu** [comment]
superseded by #239

**Pull request closed without merging**
