### PR TITLE
OWNERS: clean up

### PR DESCRIPTION
**Pull request by hexfusion**
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Review by hasbro17 — APPROVED** [review]
/lgtm

**Comment by hexfusion** [comment]
configmap-scale is broken

/overide ci/prow/configmap-scale

**Comment by hexfusion** [comment]
configmap-scale is broken

/override ci/prow/configmap-scale

https://coreos.slack.com/archives/C01GYC1RN3Y/p1636997570044000

**Comment by hexfusion** [comment]
/override ci/prow/configmap-scale



<br class="Apple-interchange-newline">

**Comment by hexfusion** [comment]
non code change CI is down

/override ci/prow/e2e-aws-serial

**Comment by hexfusion** [comment]
manually added tags as they should not be required in 4.10 dev cycle

**Pull request merged**
