### PR TITLE
[openshift-4.3] Bug 1815634: bump etcd v3.3.19

### PR DESCRIPTION
**Pull request by hexfusion**
This PR bumps 4.3 from v3.3.17 to v3.3.19 which includes important stability fixes.

v3.3.18 details https://github.com/openshift/etcd/pull/21 
v3.3.19 details #40

### CODE REVIEW

**Comment by hexfusion** [comment]
cc @deads2k @smarterclayton  @abhinavdahiya @sdodson @crawford

**Comment by alaypatel07** [comment]
/retitle [openshift-4.3] Bug 1812262: bump etcd v3.3.19

**Comment by alaypatel07** [comment]
/retitle [openshift-4.3] Bug 1815634: bump etcd v3.3.19

**Comment by hexfusion** [comment]
continued https://github.com/openshift/etcd/pull/53

**Pull request closed without merging**
