### PR TITLE
OCPBUGS-34653: Rebase etcd 3.5.14 openshift 4.17

### PR DESCRIPTION
**Pull request by Elbehery**
This PR rebases etcd 3.5.14 into openshift-4.17.

After rebasing, running `make` locally produce 

```
SUCCESS: etcd_build (GOARCH=amd64)
./bin/etcd --version
etcd Version: 3.5.14
Git SHA: b8e830c20
Go Version: go1.21.10
Go OS/Arch: darwin/amd64
./bin/etcdctl version
etcdctl version: 3.5.14
API version: 3.5
./bin/etcdutl version
etcdutl version: 3.5.14
API version: 3.5
```

cc @openshift/openshift-team-etcd

### CODE REVIEW

**Comment by Elbehery** [comment]
dropping `go toolchain` in this [commit](https://github.com/openshift/etcd/pull/273/commits/d38e5ec198d672c547b9257acd4a91206301ca24)

the docker file used in ci still on go1.20 .. we need to get a new image stream if we want to keep the directive 

cc @openshift/openshift-team-etcd

**Comment by dusk125** [comment]
@Elbehery looks like we'll have to remove the toolchain directive until we can build with 1.21

**Comment by Elbehery** [comment]
> @Elbehery looks like we'll have to remove the toolchain directive until we can build with 1.21

I already dropped them in a downstream carry [commit](https://github.com/openshift/etcd/pull/273/commits/ff0bd3b9885cade615a82ecaf4e4a1adee902b27)

**Comment by Elbehery** [comment]
@soltysh hello, we need `valid/jira` label here please :)

**Comment by soltysh** [comment]
/remove-label jira/invalid-bug
/label jira/valid-bug

this is the "master" branch for etcd

**Pull request merged**
