### PR TITLE
Dockerfile: resolve issue where binary was not properly copied

### PR DESCRIPTION
**Pull request by hexfusion**
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by hexfusion** [comment]
@deads2k

**Comment by deads2k** [comment]
images built.  This looks like a good revert of https://github.com/openshift/etcd/commit/e9ac712ced876a8963a166c97b309b07276bb9d7 which is a very likely culprit. merging to hit the next payload build.  

units were already failing.

**Pull request merged**
