### PR TITLE
OCPBUGS-32813: Revert "Merge pull request #261 from Elbehery/rebase-etcd-3.5.13-open…

### PR DESCRIPTION
**Pull request by dusk125**
…shift-4.14"

We're reverting this to have openshift/etcd stay in sync with the Go version expected at a given Openshift version: for 4.14, that's 1.20.

### CODE REVIEW

**Comment by dusk125** [comment]
I accidentally messed these up...fixing
/assign @sandeepknd (for the cherry-pick-approved label)
/assign @soltysh (for the jira label)

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
