### PR TITLE
ETCD-537: Revert "bump build root go1.20"

### PR DESCRIPTION
**Pull request by Elbehery**
This reverts commit 6d8f5d2ac3c1a31ad3ac56ae15717ef9856fe076.

Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by Elbehery** [comment]
@soltysh can we label `valid/jira` here plz ?

**Comment by soltysh** [comment]
Manually overriding jira label, to get to a working state again. 
/label jira/valid-bug

**Pull request merged**
