### PR TITLE
Bug OCPBUGS-3098: UPSTREAM: <carry>: server/etcdmain: add configurable cipher list to gRPC proxy listener

### PR DESCRIPTION
**Pull request by dusk125**
Carrying upstream fix for https://issues.redhat.com/browse/OCPBUGS-1123

### CODE REVIEW

**Comment by hasbro17** [comment]
We have no 4.14 yet so going to override the invalid jira label for this one.

**Comment by tjungblu** [comment]
@hasbro17 not sure tide actually caught up on the labels, but https://prow.ci.openshift.org/pr?query=is%3Apr+repo%3Aopenshift%2Fetcd+author%3Adusk125+head%3Aopenshift-4.13

reports the `bugzilla/valid-bug` label to be missing. Even though it reports to be in the merge queue here...

**Pull request merged**
