### PR TITLE
OCPBUGS-31653: Rebase etcd 3.5.13 openshift 4.13

### PR DESCRIPTION
**Pull request by Elbehery**
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow.

### CODE REVIEW

**Comment by Elbehery** [comment]
ptal @tjungblu @soltysh @sandeepknd

**Review by soltysh — APPROVED** [review]
https://github.com/openshift/etcd/pull/261 merged, so overriding jira labels
/remove-label jira/invalid-bug
/label jira/valid-bug

**Pull request merged**
