### PR TITLE
OCPBUGS-22727: [4.14] Rebase openshift/etcd to 3.5.10

### PR DESCRIPTION
**Pull request by tjungblu**

### CODE REVIEW

**Comment by tjungblu** [comment]
/hold 

waiting for 4.14.0 to be released officially

**Comment by tjungblu** [comment]
/hold cancel

4.14.0 just released

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Comment by geliu2016** [comment]
pre-merge-tested with 4.14.0-0.ci.test-2023-11-01-024017-ci-ln-pil5n6k-latest

/label qe-approved

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
