### PR TITLE
Bug 2077975: Merge tag 'v3.4.18' into 4.8 

### PR DESCRIPTION
**Pull request by Elbehery**
This PR attempts to merge upstream `v3.14.18` tag into openshift-4.8. 

This PR is a result of the following steps 

- checkout branch from openshift-4.8
- merge upstream v3.14.18 into this branch
- cherry-pick all down stream commits identified from https://github.com/openshift/etcd/pull/65/commits
- basically all the commits from `Dec 15, 2020` till the end
- cherry pick all the commits from https://github.com/openshift/etcd/commits/openshift-4.8
-  all the commits from ( Feb 6, 2021 till May 24, 2021 ) without merge commits
- run go mod tidy && go mod vendor 
- added go.mod, go.sum and vendor folder

### CODE REVIEW

**Comment by Elbehery** [comment]
/hold 

running `make` after the rebase, i found out the following 

```
./bin/etcd --version
etcd Version: 3.4.14
Git SHA: aefa6bf59
Go Version: go1.16.4
Go OS/Arch: darwin/amd64
./bin/etcdctl version
etcdctl version: 3.4.14
API version: 3.4
```

I do not know why the version still the same after merging the tag, probably the cherry-picking override something but i cant figure it out.

**Review by geliu2016 — APPROVED** [review]
/lgtm
/label cherry-pick-approved

**Comment by sdodson** [comment]
/retest-required
/unassign
/assign @tjungblu @dusk125 

@Elbehery I appreciate your requesting my review but I'm really not qualified for that :-)

**Comment by sdodson** [comment]
@Elbehery Looks like 8c8bdef231 bumped github.com/golang-jwt/jwt v3.2.2 which is beyond where upstream etcd-3.4 is and requires Go 1.15 or 1.16. Reverting that commit lets me build with 1.12.17 and yields a binary that identifies as 3.4.18, though I have no idea if reverting that commit is a real solution.

**Comment by Elbehery** [comment]
> @Elbehery Looks like [8c8bdef](https://github.com/openshift/etcd/commit/8c8bdef23166d486fc4c8f4e31c6dda7dbc2f450) bumped github.com/golang-jwt/jwt v3.2.2 which is beyond where upstream etcd-3.4 is and requires Go 1.15 or 1.16. Reverting that commit lets me build with 1.12.17 and yields a binary that identifies as 3.4.18, though I have no idea if reverting that commit is a real solution.

Thanks so much for your effort .. yes I think this could work .. Is it possible that you update this PR with your fix ?

**Comment by Elbehery** [comment]
> @Elbehery Looks like [8c8bdef](https://github.com/openshift/etcd/commit/8c8bdef23166d486fc4c8f4e31c6dda7dbc2f450) bumped github.com/golang-jwt/jwt v3.2.2 which is beyond where upstream etcd-3.4 is and requires Go 1.15 or 1.16. Reverting that commit lets me build with 1.12.17 and yields a binary that identifies as 3.4.18, though I have no idea if reverting that commit is a real solution.

Thanks so much for pointing me there .. Yes, I reverted the commit, used go.12.17 and built the project and the resulting binary was 3.4.18 .. I pushed the changes in go.mod, go.sum and vendor now

**Comment by Elbehery** [comment]
closing this in favour of https://github.com/openshift/etcd/pull/136

**Pull request closed without merging**
