### PR TITLE
[openshift-4.4] Bug 1815637: bump etcd v3.3.19

### PR DESCRIPTION
**Pull request by hexfusion**
This PR bumps etcd to v3.3.19 which includes a few important bugfixes:

**etcd server**
- Fix corruption bug in defrag. https://github.com/etcd-io/etcd/pull/11613

**client v3**
- Fix "hasleader" metadata embedding. https://github.com/etcd-io/etcd/pull/11687

**gRPC Proxy**
- Fix panic on error for metrics handler. https://github.com/etcd-io/etcd/pull/11694

Full 3.3.19 changelog: https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3319-2020-03-18

### CODE REVIEW

**Comment by hexfusion** [comment]
> Mar 20 17:22:54.826 W ns/openshift-kube-apiserver pod/kube-apiserver-ip-10-0-154-138.ec2.internal Readiness probe failed: HTTP probe failed with statuscode: 500

hmm
/test e2e-aws

**Comment by hexfusion** [comment]
running another set of tests.

/test all

**Comment by hexfusion** [comment]
retesting everything

**Comment by hexfusion** [comment]
one more run
/test all

**Comment by hexfusion** [comment]
> --- FAIL: TestRoundRobinBalancedResolvableFailoverFromRequestFail (0.04s)
    balancer_test.go:308: expected balanced loads for 20 requests, got switches 3

I have seen this before

/test unit

**Comment by hexfusion** [comment]
more soak
/test all

**Comment by hexfusion** [comment]
one more last was all green

/test all

**Comment by hexfusion** [comment]
cc @deads2k @smarterclayton  @abhinavdahiya @sdodson @crawford

**Comment by sdodson** [comment]
Sorry for silly first time looking at this repo questions, but are we forked from upstream or does this match upstream 3.3.19 exactly?

**Comment by hexfusion** [comment]
we are forked from upstream regarding the repo. the branch is rebased against the upstream v3.3.19 tag. So we are carrying some patches (not to etcd) on top of v3.3.19.

**Comment by hexfusion** [comment]
> fail [github.com/openshift/origin/test/extended/util/disruption/disruption.go:226]: Mar 25 22:04:35.476: API was unreachable during disruption for at least 8m38s of 34m35s (25%):

.. wow
/test e2e-gcp-upgrade

**Comment by hexfusion** [comment]
/hold
wait for GA

**Comment by hexfusion** [comment]
soak

/test all

**Comment by hexfusion** [comment]
this is continued on https://github.com/openshift/etcd/pull/45

**Pull request closed without merging**
