### PR TITLE
Bug 1815637: bump etcd v3.3.22

### PR DESCRIPTION
**Pull request by hexfusion**
This PR bumps etcd to v3.3.22 which includes a few important bugfixes:

**etcd server**
- Fix corruption bug in defrag. https://github.com/etcd-io/etcd/pull/11613

**client v3**
- Fix "hasleader" metadata embedding. https://github.com/etcd-io/etcd/pull/11687

**gRPC Proxy**
- Fix panic on error for metrics handler. https://github.com/etcd-io/etcd/pull/11694

3.3.19 changelog: https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3319-2020-03-18
3.3.20 changelog https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3320-2020-04-01
3.3.21 changelog https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3321-2020-05-18
3.3.22 changelog https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.3.md#v3321-2020-05-18

CARRY: https://github.com/openshift/etcd/pull/47/commits/3c5d90bd194d3f38b7f6873441bc7eada8918b1e

### CODE REVIEW

**Comment by ironcladlou** [comment]
/retitle Bug 1815637, 1823993: bump etcd v3.3.20

**Comment by hexfusion** [comment]
# soak
/test e2e-gcp-upgrade

**Comment by hexfusion** [comment]
soak

/test all

**Comment by hexfusion** [comment]
soak
/test all

**Comment by hexfusion** [comment]
soak
/test all

**Comment by hexfusion** [comment]
last soak

/retest

**Comment by hexfusion** [comment]
last soak 

/test all

**Comment by hexfusion** [comment]
> TestRoundRobinBalancedResolvableFailoverFromRequestFail
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_etcd/47/pull-ci-openshift-etcd-openshift-4.4-unit/1280177990566678528

**Comment by hexfusion** [comment]
manually adding valid bug tag as this bump is not reflective directly in 4.5 as we bump etcd minor.

**Comment by hexfusion** [comment]
git diff bmp-3.3.20..v3.3.22 &> rebase.diff.txt
[rebase.diff.txt](https://github.com/openshift/etcd/files/4905071/rebase.diff.txt)

**Comment by hexfusion** [comment]
flake
/test e2e-aws-serial

**Comment by hexfusion** [comment]
cc @sdodson

**Comment by sdodson** [comment]
I'll fix the bug after this merges.

**Comment by hexfusion** [comment]
here is to trying 
/cherry-pick release-4.3

**Comment by hexfusion** [comment]
here is to trying

/cherry-pick openshift-4.3

**Pull request merged**
