### PR TITLE
OCPBUGS-31650: Rebase etcd 3.5.13 openshift 4.14

### PR DESCRIPTION
**Pull request by Elbehery**
This PR rebases etcd 3.5.13 into openshift-4.15.

This PR has been created by this workflow 

- `git rebase --rebase-merges --fork-point v3.5.12 v3.5.13` ( rebasing the changes from upstream 3.5.12 --> 3.5.13 )
- `git cherry-pick 0404154d4247ab63b2231635c51df0a50eec4388` to cherrypick the downstream changes ([commit](https://github.com/openshift/etcd/commit/0404154d4247ab63b2231635c51df0a50eec4388))
- `git cherry-pick 740bfccd1ce952eb2bb3347f55d28adcb9a946fb` to cherrypick the downstream changes ([commit](https://github.com/openshift/etcd/commit/740bfccd1ce952eb2bb3347f55d28adcb9a946fb))

After rebasing, running `make` locally produce 

```
SUCCESS: etcd_build (GOARCH=amd64)
./bin/etcd --version
etcd Version: 3.5.13
Git SHA: 66b848b16
Go Version: go1.21.1
Go OS/Arch: darwin/amd64
./bin/etcdctl version
etcdctl version: 3.5.13
API version: 3.5
./bin/etcdutl version
etcdutl version: 3.5.13
API version: 3.5
```

cc @tjungblu @hasbro17 @dusk125 @soltysh @deads2k

### CODE REVIEW

**Comment by Elbehery** [comment]
@tjungblu shall we merge this ? 

4.16 & 4.15 rebases were not reverted, yet :D

**Comment by soltysh** [comment]
https://github.com/openshift/etcd/pull/260 merged, so overriding jira labels
/remove-label jira/invalid-bug
/label jira/valid-bug

**Pull request merged**
