### PR TITLE
OCPBUGS-28730: Rebase etcd 3.5.12 openshift 4.16

### PR DESCRIPTION
**Pull request by Elbehery**
This PR rebases etcd 3.5.12 into openshift-4.16.

This PR has been created by this workflow 

- `git rebase --rebase-merges --fork-point v3.5.11 v3.5.12` ( rebasing the changes from upstream 3.5.11 --> 3.5.12 )
- `git cherry-pick 238437916a443355e97a9b3bb0b9af96963b2b11` to cherrypick the downstream changes ([commit](https://github.com/openshift/etcd/commit/238437916a443355e97a9b3bb0b9af96963b2b11))

updated Dockerfiles && ci.operator to golang 1.20 && ocp 4.16 base image in https://github.com/openshift/etcd/commit/835278b7d8db63dfa9c413c5af24e83247b034d2

After rebasing, running `make` locally produce 

```
SUCCESS: etcd_build (GOARCH=amd64)
./bin/etcd --version
etcd Version: 3.5.12
Git SHA: 75af8a8a2
Go Version: go1.20
Go OS/Arch: darwin/amd64
./bin/etcdctl version
etcdctl version: 3.5.12
API version: 3.5
./bin/etcdutl version
etcdutl version: 3.5.12
API version: 3.5
```

cc @tjungblu @hasbro17 @dusk125 @soltysh @deads2k

### CODE REVIEW

**Comment by tjungblu** [comment]
generally looks good to me, let's do one blocking payload run for safety


/payload 4.16 nightly blocking

**Comment by Elbehery** [comment]
@deads2k @soltysh ptal if the nightlies are ok now 👍🏽 

cc @hasbro17 @dusk125

**Pull request merged**
