### PR TITLE
OCPBUGS-2142: Rebase openshift/etcd 4.10 onto 3.5.5

### PR DESCRIPTION
**Pull request by tjungblu**
This was rebased with:

> git rebase --rebase-merges --fork-point v3.5.3 v3.5.5
> git merge openshift/openshift-4.10

same as #144

### CODE REVIEW

**Comment by dusk125** [comment]
lgtm, will approve when we get another

**Review by geliu2016 — APPROVED** [review]
/label cherry-pick-approved

**Pull request merged**
