### PR TITLE
Bug 1958405: UPSTREAM: <carry>: etcdserver/api/etcdhttp: log successful etcd server side health check in debug level

### PR DESCRIPTION
**Pull request by hexfusion**
Manual cherry-pick of https://github.com/etcd-io/etcd/pull/12677 into openshift-4.8 on top of #79 

net change here is the reduction of verbosity from #79 success checks to debug

### CODE REVIEW

**Comment by hexfusion** [comment]
group lead not required to my knowledge pre code freeze

**Review by lilic — APPROVED** [review]
/lgtm

**Pull request merged**
