### PR TITLE
OCPBUGS-39188: Rebase etcd 3.5.15 openshift 4.18

### PR DESCRIPTION
**Pull request by Elbehery**
This PR rebases etcd 3.5.15 into openshift-4.18.

After rebasing, running make locally produce

```
SUCCESS: etcd_build (GOARCH=arm64)
./bin/etcd --version
etcd Version: 3.5.15
Git SHA: 1f3df475d
Go Version: go1.21.12
Go OS/Arch: darwin/arm64
./bin/etcdctl version
etcdctl version: 3.5.15
API version: 3.5
./bin/etcdutl version
etcdutl version: 3.5.15
API version: 3.5
```

cc @openshift/openshift-team-etcd

### CODE REVIEW

**Comment by Elbehery** [comment]
@tjungblu  the test `configmap-scale` is failing due to 

```
++ oc get route -n openshift-monitoring prometheus-k8s -o 'jsonpath={.spec.host}'
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
+ prom_url=https://
```


Request to override

**Comment by hasbro17** [comment]
/remove-label jira/invalid-bug
/label jira/valid-bug

There is no 4.19 branch yet and 4.18 is the master branch currently.

**Pull request closed without merging**
